//*
// CloudEvent Protobuf Format
//
// - Required context attributes are explicitly represented.
// - Optional and Extension context attributes are carried in a map structure.
// - Data may be represented as binary, text, or protobuf messages.

// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,import_extension=js"
// @generated from file io/cloudevents/v1/cloudevents.proto (package io.cloudevents.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Any, Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_any, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file io/cloudevents/v1/cloudevents.proto.
 */
export const file_io_cloudevents_v1_cloudevents: GenFile = /*@__PURE__*/
  fileDesc("CiNpby9jbG91ZGV2ZW50cy92MS9jbG91ZGV2ZW50cy5wcm90bxIRaW8uY2xvdWRldmVudHMudjEisAQKCkNsb3VkRXZlbnQSCgoCaWQYASABKAkSDgoGc291cmNlGAIgASgJEhQKDHNwZWNfdmVyc2lvbhgDIAEoCRIMCgR0eXBlGAQgASgJEkEKCmF0dHJpYnV0ZXMYBSADKAsyLS5pby5jbG91ZGV2ZW50cy52MS5DbG91ZEV2ZW50LkF0dHJpYnV0ZXNFbnRyeRIVCgtiaW5hcnlfZGF0YRgGIAEoDEgAEhMKCXRleHRfZGF0YRgHIAEoCUgAEioKCnByb3RvX2RhdGEYCCABKAsyFC5nb29nbGUucHJvdG9idWYuQW55SAAaaQoPQXR0cmlidXRlc0VudHJ5EgsKA2tleRgBIAEoCRJFCgV2YWx1ZRgCIAEoCzI2LmlvLmNsb3VkZXZlbnRzLnYxLkNsb3VkRXZlbnQuQ2xvdWRFdmVudEF0dHJpYnV0ZVZhbHVlOgI4ARrTAQoYQ2xvdWRFdmVudEF0dHJpYnV0ZVZhbHVlEhQKCmNlX2Jvb2xlYW4YASABKAhIABIUCgpjZV9pbnRlZ2VyGAIgASgFSAASEwoJY2Vfc3RyaW5nGAMgASgJSAASEgoIY2VfYnl0ZXMYBCABKAxIABIQCgZjZV91cmkYBSABKAlIABIUCgpjZV91cmlfcmVmGAYgASgJSAASMgoMY2VfdGltZXN0YW1wGAcgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEgAQgYKBGF0dHJCBgoEZGF0YSJACg9DbG91ZEV2ZW50QmF0Y2gSLQoGZXZlbnRzGAEgAygLMh0uaW8uY2xvdWRldmVudHMudjEuQ2xvdWRFdmVudELGAQoXaW8uY2xvdWRldmVudHMudjEucHJvdG9QAVpVZ2l0aHViLmNvbS9zb3VuZHBoaWxvc29waGVyL2Jhc2ljLWdycGMtc2VydmljZS1nby9zZGsvaW8vY2xvdWRldmVudHMvdjE7Y2xvdWRldmVudHNWMaoCGkNsb3VkTmF0aXZlLkNsb3VkRXZlbnRzLlYxygIXSW9cQ2xvdWRFdmVudHNcVjFcUHJvdG/qAhpJbzo6Q2xvdWRFdmVudHM6OlYxOjpQcm90b2IGcHJvdG8z", [file_google_protobuf_any, file_google_protobuf_timestamp]);

/**
 * @generated from message io.cloudevents.v1.CloudEvent
 */
export type CloudEvent = Message<"io.cloudevents.v1.CloudEvent"> & {
  /**
   * Required Attributes
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * URI-reference
   *
   * @generated from field: string source = 2;
   */
  source: string;

  /**
   * @generated from field: string spec_version = 3;
   */
  specVersion: string;

  /**
   * @generated from field: string type = 4;
   */
  type: string;

  /**
   * Optional & Extension Attributes
   *
   * @generated from field: map<string, io.cloudevents.v1.CloudEvent.CloudEventAttributeValue> attributes = 5;
   */
  attributes: { [key: string]: CloudEvent_CloudEventAttributeValue };

  /**
   * -- CloudEvent Data (Bytes, Text, or Proto)
   *
   * @generated from oneof io.cloudevents.v1.CloudEvent.data
   */
  data: {
    /**
     * @generated from field: bytes binary_data = 6;
     */
    value: Uint8Array;
    case: "binaryData";
  } | {
    /**
     * @generated from field: string text_data = 7;
     */
    value: string;
    case: "textData";
  } | {
    /**
     * @generated from field: google.protobuf.Any proto_data = 8;
     */
    value: Any;
    case: "protoData";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message io.cloudevents.v1.CloudEvent.
 * Use `create(CloudEventSchema)` to create a new message.
 */
export const CloudEventSchema: GenMessage<CloudEvent> = /*@__PURE__*/
  messageDesc(file_io_cloudevents_v1_cloudevents, 0);

/**
 * @generated from message io.cloudevents.v1.CloudEvent.CloudEventAttributeValue
 */
export type CloudEvent_CloudEventAttributeValue = Message<"io.cloudevents.v1.CloudEvent.CloudEventAttributeValue"> & {
  /**
   * @generated from oneof io.cloudevents.v1.CloudEvent.CloudEventAttributeValue.attr
   */
  attr: {
    /**
     * @generated from field: bool ce_boolean = 1;
     */
    value: boolean;
    case: "ceBoolean";
  } | {
    /**
     * @generated from field: int32 ce_integer = 2;
     */
    value: number;
    case: "ceInteger";
  } | {
    /**
     * @generated from field: string ce_string = 3;
     */
    value: string;
    case: "ceString";
  } | {
    /**
     * @generated from field: bytes ce_bytes = 4;
     */
    value: Uint8Array;
    case: "ceBytes";
  } | {
    /**
     * @generated from field: string ce_uri = 5;
     */
    value: string;
    case: "ceUri";
  } | {
    /**
     * @generated from field: string ce_uri_ref = 6;
     */
    value: string;
    case: "ceUriRef";
  } | {
    /**
     * @generated from field: google.protobuf.Timestamp ce_timestamp = 7;
     */
    value: Timestamp;
    case: "ceTimestamp";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message io.cloudevents.v1.CloudEvent.CloudEventAttributeValue.
 * Use `create(CloudEvent_CloudEventAttributeValueSchema)` to create a new message.
 */
export const CloudEvent_CloudEventAttributeValueSchema: GenMessage<CloudEvent_CloudEventAttributeValue> = /*@__PURE__*/
  messageDesc(file_io_cloudevents_v1_cloudevents, 0, 0);

/**
 * @generated from message io.cloudevents.v1.CloudEventBatch
 */
export type CloudEventBatch = Message<"io.cloudevents.v1.CloudEventBatch"> & {
  /**
   * @generated from field: repeated io.cloudevents.v1.CloudEvent events = 1;
   */
  events: CloudEvent[];
};

/**
 * Describes the message io.cloudevents.v1.CloudEventBatch.
 * Use `create(CloudEventBatchSchema)` to create a new message.
 */
export const CloudEventBatchSchema: GenMessage<CloudEventBatch> = /*@__PURE__*/
  messageDesc(file_io_cloudevents_v1_cloudevents, 1);

