// @generated by protoc-gen-es v2.6.3 with parameter "target=ts,import_extension=js"
// @generated from file basic/v1/basic.proto (package basic.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { BackgroundRequestSchema, BackgroundResponseSchema, HelloRequestSchema, HelloResponseSchema, TalkRequestSchema, TalkResponseSchema } from "../service/v1/service_pb.js";
import { file_basic_service_v1_service } from "../service/v1/service_pb.js";

/**
 * Describes the file basic/v1/basic.proto.
 */
export const file_basic_v1_basic: GenFile = /*@__PURE__*/
  fileDesc("ChRiYXNpYy92MS9iYXNpYy5wcm90bxIIYmFzaWMudjEyhAIKDEJhc2ljU2VydmljZRJKCgVIZWxsbxIeLmJhc2ljLnNlcnZpY2UudjEuSGVsbG9SZXF1ZXN0Gh8uYmFzaWMuc2VydmljZS52MS5IZWxsb1Jlc3BvbnNlIgASSwoEVGFsaxIdLmJhc2ljLnNlcnZpY2UudjEuVGFsa1JlcXVlc3QaHi5iYXNpYy5zZXJ2aWNlLnYxLlRhbGtSZXNwb25zZSIAKAEwARJbCgpCYWNrZ3JvdW5kEiMuYmFzaWMuc2VydmljZS52MS5CYWNrZ3JvdW5kUmVxdWVzdBokLmJhc2ljLnNlcnZpY2UudjEuQmFja2dyb3VuZFJlc3BvbnNlIgAwAUJIWkZnaXRodWIuY29tL3NvdW5kcGhpbG9zb3BoZXIvYmFzaWMtZ3JwYy1zZXJ2aWNlLWdvL3Nkay9iYXNpYy92MTtiYXNpY1YxYgZwcm90bzM", [file_basic_service_v1_service]);

/**
 * @generated from service basic.v1.BasicService
 */
export const BasicService: GenService<{
  /**
   * @generated from rpc basic.v1.BasicService.Hello
   */
  hello: {
    methodKind: "unary";
    input: typeof HelloRequestSchema;
    output: typeof HelloResponseSchema;
  },
  /**
   * @generated from rpc basic.v1.BasicService.Talk
   */
  talk: {
    methodKind: "bidi_streaming";
    input: typeof TalkRequestSchema;
    output: typeof TalkResponseSchema;
  },
  /**
   * @generated from rpc basic.v1.BasicService.Background
   */
  background: {
    methodKind: "server_streaming";
    input: typeof BackgroundRequestSchema;
    output: typeof BackgroundResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_basic_v1_basic, 0);

