// @generated by protoc-gen-connect-query v2.1.1 with parameter "target=ts,import_extension=js"
// @generated from file basic/v1/basic.proto (package basic.v1, syntax proto3)
/* eslint-disable */

import { BasicService } from "./basic_pb.js";

/**
 * @generated from rpc basic.v1.BasicService.Hello
 */
export const hello = BasicService.method.hello;
