// @generated by protoc-gen-es v2.6.3 with parameter "target=ts,import_extension=js"
// @generated from file basic/service/v1/service.proto (package basic.service.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { CloudEvent } from "../../../io/cloudevents/v1/cloudevents_pb.js";
import { file_io_cloudevents_v1_cloudevents } from "../../../io/cloudevents/v1/cloudevents_pb.js";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file basic/service/v1/service.proto.
 */
export const file_basic_service_v1_service: GenFile = /*@__PURE__*/
  fileDesc("Ch5iYXNpYy9zZXJ2aWNlL3YxL3NlcnZpY2UucHJvdG8SEGJhc2ljLnNlcnZpY2UudjEiLgoPU29tZVNlcnZpY2VEYXRhEg0KBXZhbHVlGAEgASgJEgwKBHR5cGUYAiABKAkicQoTU29tZVNlcnZpY2VSZXNwb25zZRIKCgJpZBgBIAEoCRIMCgRuYW1lGAIgASgJEg8KB3ZlcnNpb24YAyABKAkSLwoEZGF0YRgEIAEoCzIhLmJhc2ljLnNlcnZpY2UudjEuU29tZVNlcnZpY2VEYXRhIlAKFFNvbWVTZXJ2aWNlUmVzcG9uc2VzEjgKCXJlc3BvbnNlcxgBIAMoCzIlLmJhc2ljLnNlcnZpY2UudjEuU29tZVNlcnZpY2VSZXNwb25zZSIfCgxIZWxsb1JlcXVlc3QSDwoHbWVzc2FnZRgBIAEoCSJDCg1IZWxsb1Jlc3BvbnNlEjIKC2Nsb3VkX2V2ZW50GAEgASgLMh0uaW8uY2xvdWRldmVudHMudjEuQ2xvdWRFdmVudCImChJIZWxsb1Jlc3BvbnNlRXZlbnQSEAoIZ3JlZXRpbmcYASABKAkiHgoLVGFsa1JlcXVlc3QSDwoHbWVzc2FnZRgBIAEoCSIeCgxUYWxrUmVzcG9uc2USDgoGYW5zd2VyGAEgASgJIiYKEUJhY2tncm91bmRSZXF1ZXN0EhEKCXByb2Nlc3NlcxgBIAEoAyJIChJCYWNrZ3JvdW5kUmVzcG9uc2USMgoLY2xvdWRfZXZlbnQYASABKAsyHS5pby5jbG91ZGV2ZW50cy52MS5DbG91ZEV2ZW50It0BChdCYWNrZ3JvdW5kUmVzcG9uc2VFdmVudBImCgVzdGF0ZRgBIAEoDjIXLmJhc2ljLnNlcnZpY2UudjEuU3RhdGUSLgoKc3RhcnRlZF9hdBgCIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASMAoMY29tcGxldGVkX2F0GAMgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBI4CglyZXNwb25zZXMYBCADKAsyJS5iYXNpYy5zZXJ2aWNlLnYxLlNvbWVTZXJ2aWNlUmVzcG9uc2UqdQoFU3RhdGUSFQoRU1RBVEVfVU5TUEVDSUZJRUQQABIRCg1TVEFURV9QUk9DRVNTEAESEgoOU1RBVEVfQ09NUExFVEUQAhIPCgtTVEFURV9FUlJPUhADEh0KGVNUQVRFX0NPTVBMRVRFX1dJVEhfRVJST1IQBEJXWlVnaXRodWIuY29tL3NvdW5kcGhpbG9zb3BoZXIvYmFzaWMtZ3JwYy1zZXJ2aWNlLWdvL3Nkay9iYXNpYy9zZXJ2aWNlL3YxO2Jhc2ljU2VydmljZVYxYgZwcm90bzM", [file_io_cloudevents_v1_cloudevents, file_google_protobuf_timestamp]);

/**
 * @generated from message basic.service.v1.SomeServiceData
 */
export type SomeServiceData = Message<"basic.service.v1.SomeServiceData"> & {
  /**
   * @generated from field: string value = 1;
   */
  value: string;

  /**
   * @generated from field: string type = 2;
   */
  type: string;
};

/**
 * Describes the message basic.service.v1.SomeServiceData.
 * Use `create(SomeServiceDataSchema)` to create a new message.
 */
export const SomeServiceDataSchema: GenMessage<SomeServiceData> = /*@__PURE__*/
  messageDesc(file_basic_service_v1_service, 0);

/**
 * @generated from message basic.service.v1.SomeServiceResponse
 */
export type SomeServiceResponse = Message<"basic.service.v1.SomeServiceResponse"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string version = 3;
   */
  version: string;

  /**
   * @generated from field: basic.service.v1.SomeServiceData data = 4;
   */
  data?: SomeServiceData;
};

/**
 * Describes the message basic.service.v1.SomeServiceResponse.
 * Use `create(SomeServiceResponseSchema)` to create a new message.
 */
export const SomeServiceResponseSchema: GenMessage<SomeServiceResponse> = /*@__PURE__*/
  messageDesc(file_basic_service_v1_service, 1);

/**
 * @generated from message basic.service.v1.SomeServiceResponses
 */
export type SomeServiceResponses = Message<"basic.service.v1.SomeServiceResponses"> & {
  /**
   * @generated from field: repeated basic.service.v1.SomeServiceResponse responses = 1;
   */
  responses: SomeServiceResponse[];
};

/**
 * Describes the message basic.service.v1.SomeServiceResponses.
 * Use `create(SomeServiceResponsesSchema)` to create a new message.
 */
export const SomeServiceResponsesSchema: GenMessage<SomeServiceResponses> = /*@__PURE__*/
  messageDesc(file_basic_service_v1_service, 2);

/**
 * @generated from message basic.service.v1.HelloRequest
 */
export type HelloRequest = Message<"basic.service.v1.HelloRequest"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message basic.service.v1.HelloRequest.
 * Use `create(HelloRequestSchema)` to create a new message.
 */
export const HelloRequestSchema: GenMessage<HelloRequest> = /*@__PURE__*/
  messageDesc(file_basic_service_v1_service, 3);

/**
 * @generated from message basic.service.v1.HelloResponse
 */
export type HelloResponse = Message<"basic.service.v1.HelloResponse"> & {
  /**
   * @generated from field: io.cloudevents.v1.CloudEvent cloud_event = 1;
   */
  cloudEvent?: CloudEvent;
};

/**
 * Describes the message basic.service.v1.HelloResponse.
 * Use `create(HelloResponseSchema)` to create a new message.
 */
export const HelloResponseSchema: GenMessage<HelloResponse> = /*@__PURE__*/
  messageDesc(file_basic_service_v1_service, 4);

/**
 * @generated from message basic.service.v1.HelloResponseEvent
 */
export type HelloResponseEvent = Message<"basic.service.v1.HelloResponseEvent"> & {
  /**
   * @generated from field: string greeting = 1;
   */
  greeting: string;
};

/**
 * Describes the message basic.service.v1.HelloResponseEvent.
 * Use `create(HelloResponseEventSchema)` to create a new message.
 */
export const HelloResponseEventSchema: GenMessage<HelloResponseEvent> = /*@__PURE__*/
  messageDesc(file_basic_service_v1_service, 5);

/**
 * @generated from message basic.service.v1.TalkRequest
 */
export type TalkRequest = Message<"basic.service.v1.TalkRequest"> & {
  /**
   * @generated from field: string message = 1;
   */
  message: string;
};

/**
 * Describes the message basic.service.v1.TalkRequest.
 * Use `create(TalkRequestSchema)` to create a new message.
 */
export const TalkRequestSchema: GenMessage<TalkRequest> = /*@__PURE__*/
  messageDesc(file_basic_service_v1_service, 6);

/**
 * @generated from message basic.service.v1.TalkResponse
 */
export type TalkResponse = Message<"basic.service.v1.TalkResponse"> & {
  /**
   * @generated from field: string answer = 1;
   */
  answer: string;
};

/**
 * Describes the message basic.service.v1.TalkResponse.
 * Use `create(TalkResponseSchema)` to create a new message.
 */
export const TalkResponseSchema: GenMessage<TalkResponse> = /*@__PURE__*/
  messageDesc(file_basic_service_v1_service, 7);

/**
 * @generated from message basic.service.v1.BackgroundRequest
 */
export type BackgroundRequest = Message<"basic.service.v1.BackgroundRequest"> & {
  /**
   * @generated from field: int64 processes = 1;
   */
  processes: bigint;
};

/**
 * Describes the message basic.service.v1.BackgroundRequest.
 * Use `create(BackgroundRequestSchema)` to create a new message.
 */
export const BackgroundRequestSchema: GenMessage<BackgroundRequest> = /*@__PURE__*/
  messageDesc(file_basic_service_v1_service, 8);

/**
 * @generated from message basic.service.v1.BackgroundResponse
 */
export type BackgroundResponse = Message<"basic.service.v1.BackgroundResponse"> & {
  /**
   * @generated from field: io.cloudevents.v1.CloudEvent cloud_event = 1;
   */
  cloudEvent?: CloudEvent;
};

/**
 * Describes the message basic.service.v1.BackgroundResponse.
 * Use `create(BackgroundResponseSchema)` to create a new message.
 */
export const BackgroundResponseSchema: GenMessage<BackgroundResponse> = /*@__PURE__*/
  messageDesc(file_basic_service_v1_service, 9);

/**
 * @generated from message basic.service.v1.BackgroundResponseEvent
 */
export type BackgroundResponseEvent = Message<"basic.service.v1.BackgroundResponseEvent"> & {
  /**
   * @generated from field: basic.service.v1.State state = 1;
   */
  state: State;

  /**
   * @generated from field: google.protobuf.Timestamp started_at = 2;
   */
  startedAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp completed_at = 3;
   */
  completedAt?: Timestamp;

  /**
   * @generated from field: repeated basic.service.v1.SomeServiceResponse responses = 4;
   */
  responses: SomeServiceResponse[];
};

/**
 * Describes the message basic.service.v1.BackgroundResponseEvent.
 * Use `create(BackgroundResponseEventSchema)` to create a new message.
 */
export const BackgroundResponseEventSchema: GenMessage<BackgroundResponseEvent> = /*@__PURE__*/
  messageDesc(file_basic_service_v1_service, 10);

/**
 * @generated from enum basic.service.v1.State
 */
export enum State {
  /**
   * @generated from enum value: STATE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: STATE_PROCESS = 1;
   */
  PROCESS = 1,

  /**
   * @generated from enum value: STATE_COMPLETE = 2;
   */
  COMPLETE = 2,

  /**
   * @generated from enum value: STATE_ERROR = 3;
   */
  ERROR = 3,

  /**
   * @generated from enum value: STATE_COMPLETE_WITH_ERROR = 4;
   */
  COMPLETE_WITH_ERROR = 4,
}

/**
 * Describes the enum basic.service.v1.State.
 */
export const StateSchema: GenEnum<State> = /*@__PURE__*/
  enumDesc(file_basic_service_v1_service, 0);

